# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49db74c8ad16528d4747e169d89e256b50b7a82211b27e64577e404c87d3dfcb8baf5bd2928b32119ee5b8f75798be71394d1508ffc7d7c90ecd4bc0e35e0259

test:
  secret_key_base: cdc20744dfe917cadd291eae238ae0f8ae513ff07b03cd9e56425f6c245e62cea69f42603d684c9939b5b4e003eed671e7b8f6dc991173828a79878bad266cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
